[package]
name = "poseidon252"
version = "0.10.0"
authors = [
  "zer0 <matteo@dusk.network>",	"vlopes11 <victor@dusk.network>",	"CPerezz <carlos@dusk.network>", "Kristoffer Ström <kristoffer@dusk.network>"
]
edition = "2018"

[dependencies]
kelvin = { path = "../kelvin" }
nstack = { path = "../nstack" }
lazy_static = "1.3.0"
hades252 = { git = "https://github.com/dusk-network/hades252", branch = "derive_canon" }
dusk-plonk = { git = "https://github.com/dusk-network/plonk", branch = "derive_canon", features = ["trace-print"]}
anyhow = "1.0"
thiserror = "1.0"
canonical = "0.1.0"
canonical_derive = "0.1.0"

[dev-dependencies]
rand = "0.7"
rand_core = "0.5"
criterion = "0.3"

[profile.dev]
opt-level = 3
debug = false
rpath = false
lto = false
debug-assertions = false
codegen-units = 16
panic = 'unwind'
incremental = false
overflow-checks = false


[profile.release]
debug = false
panic = 'abort'
lto = true
incremental = false
codegen-units = 1
