[package]
name = "poseidon252"
version = "0.13.2"
authors = [
  "zer0 <matteo@dusk.network>",	"vlopes11 <victor@dusk.network>",	"CPerezz <carlos@dusk.network>", "Kristoffer Ström <kristoffer@dusk.network>"
]
edition = "2018"

[dependencies]
lazy_static = "1.3.0"
hades252 = { git = "https://github.com/dusk-network/hades252", tag = "v0.10.1", default-features = false }
dusk-plonk = {version = "0.3", default-features = false}
dusk-bls12_381 = {version = "0.3", default-features = false}
dusk-jubjub = {version = "0.5", default-features = false}

anyhow = "1.0"
thiserror = "1.0"
canonical = {version = "0.4", optional = true}
canonical_derive = {version = "0.4", optional = true}
microkelvin = {version = "0.5", optional = true}
nstack = {version = "0.6", optional = true}

[dev-dependencies]
canonical_host = {version = "0.4"}
rand = "0.7"
rand_core = "0.5"
criterion = "0.3"

[features]
default = ["hades252/default", "dusk-bls12_381/default", "dusk-jubjub/std"]
canon = ["canonical", "canonical_derive", "nstack", "microkelvin", "dusk-bls12_381/canon", "dusk-jubjub/canon"]
canon_host = ["canon", "canonical/host"]


[profile.dev]
opt-level = 3
debug = false
rpath = false
lto = false
debug-assertions = false
codegen-units = 16
panic = 'unwind'
incremental = false
overflow-checks = false

[profile.release]
debug = false
panic = 'abort'
lto = true
incremental = false
codegen-units = 1
